---
title: "Pruebas FCAR"
author: "D. de Fez"
date: "7/8/2022"
output: pdf_document
---

```{r setup, include=FALSE}
options("tikzLatex"='C:/Users/Daniel/AppData/Local/Programs/MiKTeX/miktex/bin/x64/pdflatex.exe')
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(igraph)
library(dplyr)
library(printr)
library(tidyverse)
library(partialFcaR)

comida <- read.csv("C:\\TFG\\GitPartial\\partialFcaR\\data\\simple_comida.csv")

rownames(comida) <- comida[,1]
comida[1] <- NULL
```

```{r}
comidaspfc <- PartialFormalContext$new(comida)
```


```{r}
comidaspfc$objects 
```

```{r}
comidaspfc$attributes 
```

```{r}
print(comidaspfc)
```
```{r}
print(comidaspfc$I)
```

```{r}
comidaspfc$to_latex()
```


```{r}
comidaspfc$plot()

#comidaspfc$plot(to_latex = TRUE)
```

```{r}
attr_comida <- comidaspfc$attributes

Sparse1 <- Set$new(attributes = attr_comida)
Sparse1$assign(Carne = -1)
```

> Asignamos las variables de las que obtendremos el concepto en el set y haremos primero un extent para obtener los objetos relevantes y luego todos los atributos que harán el cierre.

```{r}
Sparse1Extent <- comidaspfc$extent(Sparse1)
Sparse1Extent
```

```{r}
Sparse1Closure <- comidaspfc$intent(Sparse1Extent)
Sparse1Closure
```


```{r}
Sparse1Closure <- comidaspfc$closure(Sparse1)
Sparse1Closure
```

```{r}
obj_comida <- comidaspfc$objects

Sparse2 <- Set$new(attributes = obj_comida)
Sparse2$assign(Pizza = 1)

Sparse2Intent <- comidaspfc$intent(Sparse2)
Sparse2Intent
```

```{r}
comidaspfc$find_concepts()

comidaspfc$concepts
```

```{r}
comidaspfc$concepts$plot()
```


```{r}
comidaspfc$find_implications()
comidaspfc$implications
```

```{r}
Sparse3 <- Set$new(attributes = attr_comida)
Sparse3$assign(Fresa = 1)

ImplicationsResult <- comidaspfc$process_implications(Sparse3)
ImplicationsResult
```
